---
GitHub Actions:
  - .github/workflows/**/*
  - .github/dependabot.yml
  - .github/labeler.yml
  - .github/.typos_config.toml

libedax:
  - scripts/build_edax_runner.sh
  - scripts/fetch_libedax_assets.sh
  - resources/dll/**/*
