name: edax_runner
version: 1.8.0
description: tiny tool for edax-reversi auto learning
homepage: https://github.com/sensuikan1973/edax_runner

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  analyzer: ^3.2.0
  coverage: ^1.1.0 # See: https://github.com/dart-lang/test/issues/1265
  pedantic_sensuikan1973: ^3.1.0
  test: ^1.20.1
