---
name: edax_runner
version: 2.14.0
description: tiny tool for edax-reversi auto learning with learning_list.txt
publish_to: none
homepage: https://github.com/sensuikan1973/edax_runner
issue_tracker: https://github.com/sensuikan1973/edax_runner/issues

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  libedax4dart: ^5.12.0
  meta: ^1.9.0

dev_dependencies:
  analyzer: ^5.5.0
  cider: ^0.1.3
  pedantic_sensuikan1973: ^4.2.0
