name: edax_runner
version: 0.1.0
description: simple cli tool for auto learning by edax-reversi
author: Naoki Shimizu
homepage: https://github.com/sensuikan1973/edax_runner

environment:
  sdk: '>2.10.0 <3.0.0'

dev_dependencies:
  analyzer: ^0.41.1
  pedantic_sensuikan1973: any
  test: ^1.15.7
