---
name: edax_runner
version: 2.0.0
description: tiny tool for edax-reversi auto learning with `learning_list.txt`
homepage: https://github.com/sensuikan1973/edax_runner

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  analyzer: ^4.0.0
  coverage: ^1.2.0 # See: https://github.com/dart-lang/test/issues/1265
  libedax4dart: ^3.4.0
  pedantic_sensuikan1973: ^3.1.0
  test: ^1.21.1
