---
name: edax_runner
version: 2.16.0
description: tiny tool for edax-reversi auto learning with learning_list.txt
publish_to: none
homepage: https://github.com/sensuikan1973/edax_runner
issue_tracker: https://github.com/sensuikan1973/edax_runner/issues

environment:
  sdk: ">=2.19.3 <4.0.0"

dependencies:
  libedax4dart: ^5.13.0
  meta: ^1.9.0

dev_dependencies:
  analyzer: ^5.7.1
  cider: ^0.1.4
  pedantic_sensuikan1973: ^4.3.0
