---
name: edax_runner
version: 3.4.0
description: tiny tool for edax-reversi auto learning with learning_list.txt
publish_to: none
homepage: https://github.com/sensuikan1973/edax_runner
issue_tracker: https://github.com/sensuikan1973/edax_runner/issues

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  libedax4dart: ^7.36.0
  meta: ^1.16.0

dev_dependencies:
  analyzer: ^7.2.0
  pedantic_sensuikan1973: ^5.10.0
