name: edax_runner
version: 1.3.0
description: tiny tool for edax-reversi auto learning
homepage: https://github.com/sensuikan1973/edax_runner

environment:
  sdk: '>=2.15.0-0 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  analyzer: ^2.4.0
  coverage: ^1.0.3 # See: https://github.com/dart-lang/test/issues/1265
  pedantic_sensuikan1973: any
  test: ^1.18.2
