name: edax_runner
version: 0.7.1
description: tiny tool for edax-reversi auto learning
author: Naoki Shimizu
homepage: https://github.com/sensuikan1973/edax_runner

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  analyzer: ^1.7.1
  coverage: ^1.0.3 # See: https://github.com/dart-lang/test/issues/1265
  pedantic_sensuikan1973: any
  test: ^1.17.7
