---
name: edax_runner
version: 2.27.0
description: tiny tool for edax-reversi auto learning with learning_list.txt
publish_to: none
homepage: https://github.com/sensuikan1973/edax_runner
issue_tracker: https://github.com/sensuikan1973/edax_runner/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  libedax4dart: ^7.0.0
  meta: ^1.9.1

dev_dependencies:
  analyzer: ^6.0.0
  cider: ^0.2.1
  pedantic_sensuikan1973: ^5.2.0
