---
name: edax_runner
version: 2.32.0
description: tiny tool for edax-reversi auto learning with learning_list.txt
publish_to: none
homepage: https://github.com/sensuikan1973/edax_runner
issue_tracker: https://github.com/sensuikan1973/edax_runner/issues

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  libedax4dart: ^7.17.0
  meta: ^1.11.0

dev_dependencies:
  analyzer: ^6.3.0
  cider: ^0.2.4
  pedantic_sensuikan1973: ^5.3.0
