name: edax_runner
version: 0.6.2
description: tiny tool for edax-reversi auto learning
author: Naoki Shimizu
homepage: https://github.com/sensuikan1973/edax_runner

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  analyzer: ^1.5.0
  coverage: ^1.0.2 # See: https://github.com/dart-lang/test/issues/1265
  pedantic_sensuikan1973: any
  test: ^1.17.2
