---
name: Create Release

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  create_release:
    # See: .github/workflows/create_release_pr.yaml
    if: ${{ github.head_ref == 'prepare_for_release' && github.event.pull_request.merged == true }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include: # See: https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
          - os: ubuntu-latest
            edax_runner_bin_name: edax_runner
            libedax_shared_library_name: libedax.so
          - os: windows-latest
            edax_runner_bin_name: edax_runner.exe
            libedax_shared_library_name: libedax-x64.dll
          - os: macos-latest
            edax_runner_bin_name: edax_runner
            libedax_shared_library_name: libedax.universal.dylib

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: install dependencies
        run: dart pub get

      - name: build edax_runner
        shell: bash
        run: ./scripts/build_edax_runner.sh ${{ matrix.edax_runner_bin_name }} ${{ matrix.libedax_shared_library_name }}

      - name: output build info
        shell: bash
        run: .github/scripts/output_build_info.sh build

      - name: inject current version
        shell: bash
        run: echo "CURRENT_VERSION=$(dart pub run cider version)" >> $GITHUB_ENV

      - name: compress files (Windows)
        if: runner.os == 'Windows'
        run: powershell Compress-Archive -Path build -DestinationPath edax_runner-${{ runner.os }}.zip
      - name: compress files (Linux, MacOS)
        if: runner.os == 'macOS' || runner.os == 'Linux'
        run: zip -r edax_runner-${{ runner.os }}.zip build

      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_VERSION }}
          files: edax_runner-${{ runner.os }}.zip
          generate_release_notes: true
