---
name: Dart CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dart_format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: dart format
        run: dart format . -l 120 --set-exit-if-changed

  dart_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: install dependencies
        run: dart pub get
      - name: analyzer
        run: dart analyze --fatal-infos --fatal-warnings .

  run_sample:
    needs: [dart_format, dart_analyze]
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include: # See: https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
          - os: ubuntu-latest
            cpu_arch: x64
            edax_runner_bin_name: edax_runner
            libedax_shared_library_name: libedax.so
          - os: windows-latest
            cpu_arch: x64
            edax_runner_bin_name: edax_runner.exe
            libedax_shared_library_name: libedax-x64.dll
          - os: macos-latest
            cpu_arch: x64
            edax_runner_bin_name: edax_runner
            libedax_shared_library_name: libedax.universal.dylib
          - os: macos-latest
            cpu_arch: arm64
            edax_runner_bin_name: edax_runner
            libedax_shared_library_name: libedax.universal.dylib

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          architecture: ${{ matrix.cpu_arch }}
      - name: install dependencies
        run: dart pub get
      - name: build edax_runner
        shell: bash
        run: ./scripts/build_edax_runner.sh ${{ matrix.edax_runner_bin_name }} ${{ matrix.libedax_shared_library_name }}
      - name: run edax_runner with sample assets
        run: cd build && ./${{ matrix.edax_runner_bin_name }}
