on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: dartfmt
      run: dartfmt ./ -l 120 --set-exit-if-changed
