on:
  pull_request:
    types: [opened, synchronize]
    paths: ['**.dart', 'pubspec.*', '.github/workflows/dartfmt.yaml']
  push:
    branches: [ main ]
    paths: ['**.dart', 'pubspec.*', '.github/workflows/dartfmt.yaml']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: dartfmt
      run: dartfmt ./ -l 120 --set-exit-if-changed
