# TODO: move edax-reversi build job to edax-reversi repository

name: publish_artifacts

on:
  push:
    branches: [ main ]
    paths: ['bin/**', 'lib/**', '.github/workflows/publish_artifacts.yaml', 'pubspec.*', 'edax.ini']

jobs:
  build:
    env: # See: https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idenv
      OUTPUT_DIR: edax_runner-bin
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include: # See: https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
          - os: ubuntu-latest
            edax-runner_bin_name: edax_runner-linux
            edax_build_command: make build ARCH=x64-modern COMP=gcc OS=linux
            edax_bin_name: lEdax-x64-modern
          - os: macOS-latest
            edax-runner_bin_name: edax_runner-mac
            edax_build_command: make build ARCH=x64-modern COMP=gcc OS=osx
            edax_bin_name: mEdax
          - os: windows-latest
            edax-runner_bin_name: edax_runner-windows.exe
            edax_build_command: make build ARCH=x64-modern COMP=gcc OS=windows
            edax_bin_name: wEdax-x64-modern.exe

    steps:
      - uses: actions/checkout@v2
      - name: mkdir env.OUTPUT_DIR
        run: mkdir ${{ env.OUTPUT_DIR }}

      - name: clone edax-reversi
        run: git clone --depth 1 https://github.com/abulmo/edax-reversi.git
      - name: fetch eval.dat
        working-directory: edax-reversi
        run: |
          mkdir data
          curl -OL https://github.com/abulmo/edax-reversi/releases/download/v4.4/eval.7z
          7z x eval.7z # 7z is pre-installed。See: https://github.com/actions/virtual-environments/search?q=7z
      - name: build edax
        working-directory: edax-reversi
        run: mkdir bin && cd src && ${{ matrix.edax_build_command }} && chmod +x ../bin/${{ matrix.edax_bin_name }}

      - name: copy edax-reversi binary to edax-runner build directory
        run: mv edax-reversi/bin/ ${{ env.OUTPUT_DIR }}
      - name: copy edax-reversi data to edax-runner build directory
        run: mv edax-reversi/data/ ${{ env.OUTPUT_DIR }}
      - name: copy edax.ini to edax-runner build directory
        run: mv edax.ini ${{ env.OUTPUT_DIR }}
      - name: copy learning_list.txt to edax-runner build directory
        run: mv learning_list.txt ${{ env.OUTPUT_DIR }}

      # https://blog.dantup.com/2019/11/easily-compiling-dart-to-native-executables-for-windows-linux-macos-with-github-actions/
      - uses: cedx/setup-dart@v2
      - name: install dependencies
        run: pub get
      - name: build edax-runner # https://dart.dev/tools/dart2native
        run: dart2native bin/edax_runner.dart -v -o ${{ env.OUTPUT_DIR }}/${{ matrix.edax-runner_bin_name }}

      - name: launch edax-runner test
        working-directory: ${{ env.OUTPUT_DIR }}
        run: |
          ./${{ matrix.edax-runner_bin_name }} & sleep 30
          rm *.log

      # See: https://github.com/actions/upload-artifact/issues/38
      # Workaround: https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
      - name: tar files to maintain file permissions
        run: mkdir -p dst && tar -cvf dst/${{ runner.os }}.tar ${{ env.OUTPUT_DIR }}
      - uses: actions/upload-artifact@v2
        with:
          name: edax_runner-releases
          path: dst
