---
name: publish_assets_gcc

on:
  release:
    types: [created]

jobs:
  build:
    env:
      OUTPUT_DIR: edax_runner-bin
      PUBLISH_DIR: dst
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            edax-runner_bin_name: edax_runner-linux
            edax_build_command: make build ARCH=x64-modern COMP=gcc OS=linux
            edax_bin_name: lEdax-x64-modern
          - os: windows-latest
            edax-runner_bin_name: edax_runner-windows.exe
            edax_build_command: make build ARCH=x64 COMP=gcc OS=windows
            edax_bin_name: wEdax-x64.exe
          - os: macos-latest
            edax-runner_bin_name: edax_runner-mac
            edax_build_command: make build ARCH=x64-modern COMP=gcc OS=osx
            edax_bin_name: mEdax

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1
        with:
          architecture: x64
      - name: install dependencies
        run: dart pub get

      - name: build edax-reversi
        env:
          dst: ${{ env.OUTPUT_DIR }}
          edax_build_command: ${{ matrix.edax_build_command }}
          edax_bin_name: ${{ matrix.edax_bin_name }}
        shell: bash
        run: ./scripts/build_edax.sh

      - name: build edax-runner
        run: dart compile exe bin/edax_runner.dart -v -o ${{ env.OUTPUT_DIR }}/${{ matrix.edax-runner_bin_name }}

      - name: output build info
        shell: bash
        run: .github/scripts/output_build_info.sh ${{ env.OUTPUT_DIR }} gcc

      - name: zip files (Windows)
        if: runner.os == 'Windows'
        run: mkdir -p ${{ env.PUBLISH_DIR }} && powershell Compress-Archive -Path ${{ env.OUTPUT_DIR }} -DestinationPath ${{ env.PUBLISH_DIR }}/${{ runner.os }}.zip
      - name: zip files (Linux, MacOS)
        if: runner.os == 'macOS' || runner.os == 'Linux'
        run: mkdir -p ${{ env.PUBLISH_DIR }} && zip -r ${{ env.PUBLISH_DIR }}/${{ runner.os }}.zip ${{ env.OUTPUT_DIR }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.PUBLISH_DIR }}/${{ runner.os }}.zip
          asset_name: edax_runner_${{ runner.os }}_gcc.zip
          asset_content_type: application/zip
