name: publish_assets

on:
  release:
    types: [created]

jobs:
  build:
    env:
      OUTPUT_DIR: edax_runner-bin
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            edax-runner_bin_name: edax_runner-linux
            edax_build_command: make build ARCH=x64-modern COMP=gcc OS=linux
            edax_bin_name: lEdax-x64-modern
          - os: windows-latest
            edax-runner_bin_name: edax_runner-windows.exe
            edax_build_command: make build ARCH=x64 COMP=gcc OS=windows
            edax_bin_name: wEdax-x64-modern.exe
          - os: macOS-latest
            edax-runner_bin_name: edax_runner-mac
            edax_build_command: make build ARCH=x64-modern COMP=gcc OS=osx
            edax_bin_name: mEdax

    steps:
      - uses: actions/checkout@v2

      - uses: cedx/setup-dart@v2
        with:
            architecture: x64
            release-channel: beta
      - name: install dependencies
        run: pub get

      - name: build edax-runner
        env:
          dst: ${{ env.OUTPUT_DIR }}
          bin_name: ${{ matrix.edax-runner_bin_name }}
          edax_build_command: ${{ matrix.edax_build_command }}
          edax_bin_name: ${{ matrix.edax_bin_name }}
        run: |-
          sh scripts/build_edax.sh
          dart2native bin/edax_runner.dart -v -o ${{ env.dst }}/${{ env.bin_name }}

      - name: zip files (Windows)
        if: runner.os == 'Windows'
        run: mkdir -p dst && powershell Compress-Archive -Path ${{ env.OUTPUT_DIR }} -DestinationPath dst/${{ runner.os }}.zip
      - name: zip files (Linux, MacOS)
        if: runner.os == 'macOS' || runner.os == 'Linux'
        run: mkdir -p dst && zip -r dst/${{ runner.os }}.zip ${{ env.OUTPUT_DIR }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dst/${{ runner.os }}.zip
          asset_name: edax_runner_${{ runner.os }}.zip
          asset_content_type: application/zip
