on:
  pull_request:
    types: [opened, synchronize]
    paths: ['**.dart', 'pubspec.*', '.github/workflows/unit_test.yaml']
  push:
    branches: [ main ]
    paths: ['**.dart', 'pubspec.*', '.github/workflows/unit_test.yaml']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: pub get
    - name: test
      run: pub run test ./
